name: context-test
on: push

jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - name: comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Hello from GitHub Actions! 🚀"
            })
