name: context-test
on: push

jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - name: comment
        uses: actions/github-script@v7
        with:
          script: |
            console.log(context);
